### ISSUE TITLE
no module named website

### ISSUE THREAD

**Issue by cherylhughey** [Rekoc/django-startbootstrap-clean-blog#1]
Hello.

Thanks for creating the framwork. I am trying to run it in Python 3.7.1 and Django 2.0.9, but get a "no module named website" when I start the server. Do you have any suggestions? I've tried StackOverflow to no avail. Thank you. Cheryl

**Comment by Rekoc** [comment]
Hi,

Can you give me more information about this error please & also your settings.py ? I had the same error a long time ago.
The common issue is in settings.py, the section "INSTALLED_APPS" you have the "website" app who doesn't exist in your case, just remove it and it should work.
And you very welcome :-) !

**Comment by Rekoc** [comment]
I found my mistake ... Just change in manage.py the line:
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "website.settings")
by
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "<your_app_name>.settings")

It works on my laptop. Let me know.

**Comment by cherylhughey** [comment]
Awesome. Thank you. I will try to give it ago again.
